#!/bin/bash
# Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.

export AWS_EXECUTION_ENV=AWS_Lambda_python3.9

if [ -z "$AWS_LAMBDA_EXEC_WRAPPER" ]; then
  # exec /var/lang/bin/python3.8 /var/runtime/bootstrap.py
  exec /root/miniconda3/bin/python /var/runtime/bootstrap.py
else
  wrapper="$AWS_LAMBDA_EXEC_WRAPPER"
  if [ ! -f "$wrapper" ]; then
    echo "$wrapper: does not exist"
    exit 127
  fi
  if [ ! -x "$wrapper" ]; then
    echo "$wrapper: is not an executable"
    exit 126
  fi
    # exec -- "$wrapper" /var/lang/bin/python3.8 /var/runtime/bootstrap.py
    exec -- "$wrapper" /root/miniconda3/bin/python /var/runtime/bootstrap.py
fi
